### ISSUE TITLE
"ghi comment" opens vi

### ISSUE THREAD

**Issue by pforpineapple** [stephencelis/ghi#263] opened 2015-12-09 17:44 UTC
Useful for larger comments. Similar to `git commit`

**Comment by AlexChesters** [comment] 2015-12-17 12:36
I'm not sure what this issue is here? `ghi comment` opens your `$EDITOR` by default.

**Comment by AlexChesters** [comment] 2015-12-18 11:35
Closing this as I'm not too sure what the issue is here. Please comment with more information

**Closed by AlexChesters** 2015-12-18 11:35 UTC
