### ISSUE TITLE
ghi/authorization.rb:23:in `authorize!': uninitialized constant Module::Socket (NameError)

### ISSUE THREAD

**Issue by nrvale0** [stephencelis/ghi#211] opened 2014-12-09 15:42 UTC
When trying to setup auth with the module from rubygems.org:

```ShellSession
ghi config --auth nrvale0      
Enter nrvale0's GitHub password (never stored): /home/nrvale0/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/ghi-0.9.3/lib/ghi/authorization.rb:23:in `authorize!': uninitialized constant Module::Socket (NameError)
	from /home/nrvale0/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/ghi-0.9.3/lib/ghi/commands/config.rb:27:in `execute'
	from /home/nrvale0/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/ghi-0.9.3/lib/ghi/commands/command.rb:17:in `execute'
	from /home/nrvale0/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/ghi-0.9.3/lib/ghi.rb:80:in `execute'
	from /home/nrvale0/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/ghi-0.9.3/bin/ghi:4:in `<top (required)>'
	from /home/nrvale0/.rbenv/versions/2.1.2/bin/ghi:23:in `load'
	from /home/nrvale0/.rbenv/versions/2.1.2/bin/ghi:23:in `<main>'
```

```ShellSession
gem list --local | grep ghi
ghi (0.9.3)
rbenv version
2.1.2 (set by /home/nrvale0/.rbenv/version)
```

**Comment by veganstraightedge** [comment] 2015-01-05 21:53
I get this error too on the first time running `ghi config --auth veganstraightedge`.

Same gem version.

**Comment by Pawamoy** [comment] 2015-02-25 10:00
And one more here!

**Comment by dspinellis** [comment] 2015-03-05 08:25
It looks like this is a duplicate of #166, which also contains a proposed fix.

**Comment by Pawamoy** [comment] 2015-03-05 11:28
Indeed, I added `require "socket"` at the beginning of `/var/lib/gems/1.9.1/gems/ghi-0.9.3/lib/ghi/authorization.rb` and it works now.

**Comment by AlexChesters** [comment] 2015-10-16 16:15
Hi @veganstraightedge @nrvale0 @Pawamoy,

Is this issue still occurring?

**Comment by veganstraightedge** [comment] 2015-10-16 17:06
Yep.

```
$: chruby
   ruby-2.0.0-p576
   ruby-2.1.5
   ruby-2.2.2
 * ruby-2.2.3

$: ghi -v
ghi version 0.9.3

$: ghi config --auth veganstraightedge
Enter veganstraightedge's GitHub password (never stored): /Users/s/.gem/ruby/2.2.3/gems/ghi-0.9.3/lib/ghi/authorization.rb:23:in `authorize!': uninitialized constant Module::Socket (NameError)
	from /Users/s/.gem/ruby/2.2.3/gems/ghi-0.9.3/lib/ghi/commands/config.rb:27:in `execute'
	from /Users/s/.gem/ruby/2.2.3/gems/ghi-0.9.3/lib/ghi/commands/command.rb:17:in `execute'
	from /Users/s/.gem/ruby/2.2.3/gems/ghi-0.9.3/lib/ghi.rb:80:in `execute'
	from /Users/s/.gem/ruby/2.2.3/gems/ghi-0.9.3/bin/ghi:4:in `<top (required)>'
	from /Users/s/.gem/ruby/2.2.3/bin/ghi:23:in `load'
	from /Users/s/.gem/ruby/2.2.3/bin/ghi:23:in `<main>'
```

**Comment by AlexChesters** [comment] 2015-10-16 19:18
@veganstraightedge interesting... Does the same issue occur on Ruby 2.20 and 2.0.0?

**Comment by veganstraightedge** [comment] 2015-10-18 03:53
Hmm. It works now on 2.0.0-p576, 2.1.5, and 2.2.3. ¯\_(ツ)_/¯ 
Thanks!

**Comment by AlexChesters** [comment] 2015-10-18 09:35
Weird! I'll close this for now but please reopen if you encounter this again :smile:

**Closed by AlexChesters** 2015-10-18 09:35 UTC
Labels: bug, unconfirmed
