### ISSUE TITLE
find-internet-password: illegal option -- w

### ISSUE THREAD

**Issue by jalanb** [stephencelis/ghi#186] opened 2014-06-25 11:32 UTC
Running on OS X, 10.7.5, Ruby 1.8.7, ghi 0.9.3
I frequently see the error in the title, and would appreciate any hints as to how to deal with it. Example interaction follows:

```shell
$ ghi list
⠙find-internet-password: illegal option -- w
Usage: find-internet-password [-a account] [-s server] [options...] [-g] [keychain...]
    -a  Match "account" string
    -c  Match "creator" (four-character code)
    -C  Match "type" (four-character code)
    -d  Match "securityDomain" string
    -D  Match "kind" string
    -j  Match "comment" string
    -l  Match "label" string
    -p  Match "path" string
    -P  Match port number
    -r  Match "protocol" (four-character code)
    -s  Match "server" string
    -t  Match "authenticationType" (four-character code)
    -g  Display the password for the item found
If no keychains are specified to search, the default search list is used.
        Find an internet password item.
# jalanb/kd open issues
  13: Explain to user why that directory was chosen
  12: Consider frecency @
  10: Allow user to choose time format  enhancement   ready
   9: Clean history  enhancement  @
   3: Project structure  enhancement   in progress  4 @
   2: Installation  enhancement   ready  @
   1: Improve documentation  enhancement   ready
```

**Comment by AlexChesters** [comment] 2015-10-16 21:35
Closing this issue as it seems like it only affects an old version of OS X

**Comment by skorlir** [comment] 2016-02-24 14:39
This issue also affects me on OS X Yosemite 10.10.5 - I don't know how old that is, but it's a lot newer than OS X 10.7, which I think is "Lion." Ruby is 2.0.0. ghi is latest; 1.0.4.

**Comment by AlexChesters** [comment] 2016-02-24 15:02
OS X Yosemite is only one major version behind the latest so this is more of an issue if it affects that version. What command were you running @skorlir?

**Comment by skorlir** [comment] 2016-02-24 15:04
I ran `ghi`, then `ghi config --auth <username>` with my username. No other steps, apart from `brew install`ing ghi in the first place.

**Comment by AlexChesters** [comment] 2016-02-24 15:09
@skorlir are you using SourceTree by any chance?

**Comment by skorlir** [comment] 2016-02-24 15:10
Nope. Just regular 'ol git.

If you have trouble reproducing, and are willing to point me in the right direction, I'd be glad to take a stab at fixing this and making a PR. Thought I'd offer. :smile:

**Comment by AlexChesters** [comment] 2016-02-24 15:13
This looks like it could be a duplicate of #275, can you follow the steps [here](https://github.com/stephencelis/ghi/issues/275#issuecomment-182895962) and see if they help?

**Comment by skorlir** [comment] 2016-02-24 15:17
Actually, that worked. I can't imagine how it's related to SourceTree, at least in this case, but it fixed it! Thanks!

**Comment by AlexChesters** [comment] 2016-02-24 15:17
I have absolutely no idea either. It's very strange! Glad you got sorted though @skorlir :-)

**Closed** 2016-03-02 08:52 UTC
Labels: bug, unconfirmed
